### ISSUE TITLE
error spam

### ISSUE THREAD

**Issue by VaelophisNyx** [maudlin27/M28AI#108]
most recent FAF and M28 versions; using some mods
log file here 
[game_22012735.log](https://github.com/maudlin27/M28AI/files/14531172/game_22012735.log)

Mods in use
![image](https://github.com/maudlin27/M28AI/assets/1534478/8c506adf-153d-461c-b5d7-f1858c26861c) (PJ infrastructure modified to not conflict with Brewlan and Blackops*)

Relevant error:
```
`warning: Error running lua script: ...er forged alliance\mods\m28ai\lua\ai\m28unitinfo.lua(358): bad argument #1 to `max' (number expected, got nil)
         stack traceback:
         	[C]: in function `max'
         	...er forged alliance\mods\m28ai\lua\ai\m28unitinfo.lua(358): in function `GetBuildingSize'
         	...er forged alliance\mods\m28ai\lua\ai\m28engineer.lua(14802): in function <...er forged alliance\mods\m28ai\lua\ai\m28engineer.lua:14769>`
```

logged Desync irrelevant to this report; that was caused by something else.

**Comment by maudlin27** [comment]
Do you still get this error message? I'd expect it will have been resolved a short while afterwards but it's possible the mods used mean it is still present.  Message me on discord if it is still an issue.

**Comment by VaelophisNyx** [comment]
unsure, but it can be tested some time soon

**Comment by VaelophisNyx** [comment]
So we got 1h:17m into a match with M28 and the game crashed, but, I am not confident that it was M28's fault directly
However, in the mean-time (As we're both drained as hell from playing so long against it), here's that log file?
[game_22902173.log](https://github.com/user-attachments/files/16215591/game_22902173.log)

From a cursory CTRL+F search, this particular error did not pop up?

**Comment by VaelophisNyx** [comment]
Ok we did finally get ONE match to run with no desync OR a crash, with an M28 (Easy)
and!

no log spam from it anymore (well, until the end but it was kinda stuck trying to figure out what to build as we swept up the last few units)

**Comment by maudlin27** [comment]
Based on the log, the game crashed because you ran out of memory.  As a general guide, if you open task manager and the memory usage goes above 2gb then crashing is highly likely.

Memory usage will depend on a number of factors, but if you want to reduce the likelihood of such issues there are a number of things you can do:
* Use a smaller map
* Set a lower unit cap
* Minimise the mods you're using
* Reduce the number of AI players
* Reduce the faction variance
* Dont use multiple AI mods at once

E.g. based on the log it looks like you have all the following mods enabled at once (I couldnt get the replay on FAF to load to confirm):
M28AI
BlackOps FAF: Unleashed
BrewLAN
Crustaceans Collection
BlackOps FAF: ACUs
Resource Rich
Reclaim Turret
AI-Uveso
BlackOps FAF: EXUnits
Smart Tactical Missiles
PJ Infrastructure Pack
BrewLAN: Bubble Tea
BrewLAN: Caffe Corretto

The log also features numerous error messages that are unrelated to M28AI, e.g. various references to "debug: *AIExecuteBuildStructure:..." which I assume is from Uveso AI, a number of "Error running lua script" messages which from a glance at the first few look likely to be Uveso AI and/or one of the unit mods you have enabled not allowing a unit to be destroyed
